name: Test and push to main

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-merge:
    name: Run tests and merge to main
    runs-on: ubuntu-latest

    steps:
      # grab repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get dependencies
        run: dart pub get

      - name: Run utility tests
        run: dart test test/utilities_test.dart

      - name: Run mock tests tests
        run: dart test test/mock_handler_tests.dart

      - name: Run end to end tests
        run: dart test test/integration_test.dart
